if (typeof globalThis.window === "undefined") {
  globalThis.window = {
    location: { href: "http://localhost", hostname: "localhost", protocol: "http:", host: "localhost:80", port: "", pathname: "/" },
    navigator: { userAgent: "node" },
    document: {
      addEventListener: () => {},
      removeEventListener: () => {},
      createElement: () => ({ style: {}, setAttribute: () => {}, getAttribute: () => null, classList: { add: () => {}, remove: () => {}, contains: () => false } }),
      documentElement: { style: {} },
      body: { style: {} },
    },
    localStorage: {
      getItem: () => null,
      setItem: () => {},
      removeItem: () => {},
    },
    sessionStorage: {
      getItem: () => null,
      setItem: () => {},
      removeItem: () => {},
    },
    fetch: globalThis.fetch,
    setTimeout: globalThis.setTimeout,
    setInterval: globalThis.setInterval,
    clearTimeout: globalThis.clearTimeout,
    clearInterval: globalThis.clearInterval,
    requestAnimationFrame: globalThis.requestAnimationFrame,
    cancelAnimationFrame: globalThis.cancelAnimationFrame,
    URL: globalThis.URL,
    URLSearchParams: globalThis.URLSearchParams,
    Blob: globalThis.Blob,
    File: globalThis.File,
    FormData: globalThis.FormData,
    XMLHttpRequest: globalThis.XMLHttpRequest,
    WebSocket: globalThis.WebSocket,
    Event: globalThis.Event,
    EventTarget: globalThis.EventTarget,
    MouseEvent: globalThis.MouseEvent,
    KeyboardEvent: globalThis.KeyboardEvent,
    TouchEvent: globalThis.TouchEvent,
    UIEvent: globalThis.UIEvent,
    CustomEvent: globalThis.CustomEvent,
    DocumentFragment: globalThis.DocumentFragment,
    Node: globalThis.Node,
    Element: globalThis.Element,
    HTMLElement: globalThis.HTMLElement,
    HTMLBodyElement: globalThis.HTMLBodyElement,
    HTMLDivElement: globalThis.HTMLDivElement,
    HTMLImageElement: globalThis.HTMLImageElement,
    HTMLCanvasElement: globalThis.HTMLCanvasElement,
    HTMLInputElement: globalThis.HTMLInputElement,
    HTMLTextAreaElement: globalThis.HTMLTextAreaElement,
    HTMLSelectElement: globalThis.HTMLSelectElement,
    HTMLVideoElement: globalThis.HTMLVideoElement,
    HTMLAudioElement: globalThis.HTMLAudioElement,
    HTMLIFrameElement: globalThis.HTMLIFrameElement,
    HTMLAnchorElement: globalThis.HTMLAnchorElement,
    HTMLParagraphElement: globalThis.HTMLParagraphElement,
    HTMLSpanElement: globalThis.HTMLSpanElement,
    HTMLUListElement: globalThis.HTMLUListElement,
    HTMLOListElement: globalThis.HTMLOListElement,
    HTMLTableElement: globalThis.HTMLTableElement,
    DOMParser: globalThis.DOMParser,
    XMLSerializer: globalThis.XMLSerializer,
    matchMedia: () => ({ matches: false, addListener: () => {}, removeListener: () => {} }),
    openDatabase: () => null,
    openDatabaseSync: () => null,
    crypto: globalThis.crypto,
    performance: globalThis.performance,
    console: globalThis.console,
    alert: () => {},
    confirm: () => false,
    prompt: () => null,
    escape: (str) => String(str).replace(/[&<>"']/g, (m) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[m] || m),
    unescape: (str) => String(str).replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'"),
    btoa: (str) => Buffer.from(String(str)).toString("base64"),
    atob: (str) => Buffer.from(String(str), "base64").toString("utf-8"),
    isFinite: globalThis.isFinite,
    isNaN: globalThis.isNaN,
    parseFloat: globalThis.parseFloat,
    parseInt: globalThis.parseInt,
    decodeURI: globalThis.decodeURI,
    decodeURIComponent: globalThis.decodeURIComponent,
    encodeURI: globalThis.encodeURI,
    encodeURIComponent: globalThis.encodeURIComponent,
  };
  global.window = globalThis.window;
  global.document = globalThis.window.document;
  globalThis.document = global.document;
}
